spring:
  application:
    name: Smart Factory Dashboard Service
  profiles:
    active: development
  mvc:
    formcontent:
      putfilter:
        enabled: true
  messages:
    basename: messages_ko
  jpa:
      hibernate:
        ddl-auto: none

#liquibase:
#  change-log: classpath:/db/changelog/db.changelog-master.xml

logging:
  level:
    root: INFO

---

spring:
  profiles: development
  datasource:
    url: jdbc:postgresql://10.10.31.33:5432/test
    username: postgres
    password: exem
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true


logging:
  level:
    root: DEBUG

---

spring:
  profiles: production
  datasource:
    url: jdbc:postgresql://ec2-13-58-170-70.us-east-2.compute.amazonaws.com:5432/test
    username: postgres
    password: exem
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect