SELECT 1;
-- CREATE TABLE Member(
--   id BIGINT PRIMARY KEY NOT NULL,
--   name VARCHAR
-- );

-- CREATE TABLE temp_sensor
-- (
--   s_id INTEGER PRIMARY KEY NOT NULL,
--   s_date TIMESTAMP,
--   s_humidity INTEGER,
--   s_motor INTEGER,
--   s_breakpad INTEGER,
--   s_spm INTEGER,
--   s_motorelectric INTEGER,
--   s_slideelectric INTEGER,
--   s_p0004 INTEGER,
--   s_p0006 INTEGER,
--   s_p0007 INTEGER,
--   s_p000A INTEGER,
--   s_p000C INTEGER,
--   s_p000F INTEGER,
--   s_p0016 INTEGER,
--   s_p0045 INTEGER,
--   s_p0048 INTEGER,
--   s_p0049 INTEGER,
--   s_p004A INTEGER,
--   s_p004F INTEGER,
--   s_p0050 INTEGER,
--   s_sensor01_temp NUMERIC (10, 2),
--   s_sensor01_co2 INTEGER,
--   s_sensor01_lux INTEGER,
--   s_sensor02_temp NUMERIC(10, 2),
--   s_sensor02_humid INTEGER,
--   s_sensor02_co2 INTEGER,
--   s_sensor02_lux INTEGER,
--   s_sensor03_temp NUMERIC(10, 2),
--   s_sensor03_humid INTEGER,
--   s_sensor03_co2 INTEGER,
--   s_sensor03_lux INTEGER
-- );